name: assemble

on:
  push:

jobs:
  build:
    name: Gradle Assemble
    runs-on: ubuntu-latest
    container: wpilib/roborio-cross-ubuntu:2023-22.04

    steps:
    - uses: actions/checkout@v3
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Setup and assemble
      uses: gradle/gradle-build-action@v2
      with:
        arguments: assemble
